name: Lint

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23 # Replace with the Go version you are using

      - name: install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0 # Replace with the desired golangci-lint version

      - name: Run golangci-lint
        run: |
          golangci-lint run project gogen data_model common/...
